services:
  database-mysql:
    profiles:
    - dev
    - prod
    container_name: test-bob-db-mysql
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - PMA_HOSTS=${PMA_HOSTS}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DSN=${MYSQL_DSN}
    - MYSQL_TEST_DSN=${MYSQL_TEST_DSN}
    - TZ=Asia/Tokyo
    image: mysql:8.0
    networks:
      mysql-phpmyadmin: null
    ports:
    - mode: ingress
      target: 3306
      published: "3306"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: ./volumes/mysql-data
      target: /var/lib/mysql
    - type: bind
      source: ./volumes/mysql-logs
      target: /var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db-admin-phpmyadmin:
    profiles:
    - dev
    - prod
    container_name: test-bob-dbadmin-phpmyadmin
    depends_on:
      database-mysql:
        condition: service_started
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - PMA_HOSTS=${PMA_HOSTS}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DSN=${MYSQL_DSN}
    - MYSQL_TEST_DSN=${MYSQL_TEST_DSN}
    - TZ=Asia/Tokyo
    image: phpmyadmin/phpmyadmin:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      mysql-phpmyadmin: null
    ports:
    - mode: ingress
      target: 80
      published: "88"
      protocol: tcp

  atlas-migration:
    profiles:
    - dev
    container_name: test-bob-atlas
    image: arigaio/atlas:latest
    depends_on:
      database-mysql:
        condition: service_healthy
    networks:
      - mysql-phpmyadmin
    volumes:
    - type: bind
      source: ./database
      target: /migrations
    environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - PMA_HOSTS=${PMA_HOSTS}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DSN=${MYSQL_DSN}
    - MYSQL_TEST_DSN=${MYSQL_TEST_DSN}
    command: migrate apply --url "mysql://root:${MYSQL_ROOT_PASSWORD}@database-mysql:3306/${MYSQL_DATABASE}"
    
networks:
  mysql-phpmyadmin:
